device:
  lag_scale: 1.5

  adb:
    genymotion: /opt/genymotion/tools/adb
    android_studio: /home/ubuntu/Android/Sdk/platform-tools/adb
  screen_x: 1080
  screen_y: 1920

resources:
  screen_shot_dir: resources/screen_shot/
  object_image_dir: resources/object/
  object_location: resources/object_loc.yaml

logging:
  log_dir: log/

building:
  manufacturer:
    first_manufacturer_location: [960, 610]
    num_factory: 8
    num_shop: 7

  factory:
    base_products: ['metal', 'wood', 'plastic', 'seed', 'mineral', 'chemical', 'textile', 'sugar']
    produce_list: ['metal', 'wood', 'seed', 'seed', 'plastic', 'plastic', 'mineral']

  trade_hq:
      location: [890, 540]
      search_items: ['camera', 'bar', 'lock', 'blade', 'exhaust', 'wheel']

  trade_depot:
    location: [300, 545]
