device:
  adb:
    genymotion: /opt/genymotion/tools/adb
    android_studio: /home/ubuntu/Android/Sdk/platform-tools/adb
  screen_x: 1080
  screen_y: 1920

resources:
  screen_shot_dir: resources/screen_shot/
  object_image_dir: resources/object/
  object_location: resources/object_loc.yaml

logging:
  log_dir: log/

building:
  manufacturer:
    num_factory: 7
    num_shop: 7

  factory:
    base_products: ['metal', 'wood', 'plastic', 'seed', 'mineral', 'chemical', 'textile', 'sugar']
    produce_list: ['metal', 'wood', 'wood', 'seed', 'seed', 'plastic', 'plastic']
    ad_item_list: ['mineral', 'chemical', 'textile']