from object.object import BasicObject

# Template id
OPINION_AD = 1
OPINION_HEALTH = 2
OPINION_SLEEP = 3
OPINION_FIRE = 4
OPINION_ROAD = 5
OPINION_BOOK = 6
OPINION_HOUSE = 7
OPINION_GREEN = 8
OPINION_SEA = 9
OPINION_GOV = 10
OPINION_PARK = 11
OPINION_POLICE = 12
OPINION_COFFEE = 13
OPINION_RELAX = 14
OPINION_SIMOLEON1 = 15
OPINION_SIMOLEON2 = 16

OPINION_TEMPLATE_NAME = {
    OPINION_AD: 'OPINION_AD',
    OPINION_HEALTH: 'OPINION_HEALTH',
    OPINION_SLEEP: 'OPINION_SLEEP',
    OPINION_FIRE: 'OPINION_FIRE',
    OPINION_ROAD: 'OPINION_ROAD',
    OPINION_BOOK: 'OPINION_BOOK',
    OPINION_HOUSE: 'OPINION_HOUSE',
    OPINION_GREEN: 'OPINION_GREEN',
    OPINION_SEA: 'OPINION_SEA',
    OPINION_GOV: 'OPINION_GOV',
    OPINION_PARK: 'OPINION_PARK',
    OPINION_POLICE: 'OPINION_POLICE',
    OPINION_COFFEE: 'OPINION_COFFEE',
    OPINION_RELAX: 'OPINION_RELAX',
    OPINION_SIMOLEON1: 'OPINION_SIMOLEON1',
    OPINION_SIMOLEON2: 'OPINION_SIMOLEON2'
}


class Opinion(BasicObject):
    def __init__(self):
        super().__init__("opinion")
        self.n_sample = 16
        self.threshold = 0.75